#!/usr/bin/env bash
set -euo pipefail

# Patch Android project generated by Capacitor to support opening .md files from external apps
# Usage: run after `pnpm exec cap add android` / after android project exists

PACKAGE_DIR="android/app/src/main/java/com/iliefu/wemd"
MANIFEST_FILE="android/app/src/main/AndroidManifest.xml"
MAIN_ACTIVITY_KT="${PACKAGE_DIR}/MainActivity.kt"
MAIN_ACTIVITY_JAVA="${PACKAGE_DIR}/MainActivity.java"

echo "Patching Android project..."

# Ensure manifest exists
if [ ! -f "$MANIFEST_FILE" ]; then
  echo "Warning: $MANIFEST_FILE not found. Skipping manifest patch."
else
  # Ensure activity has android:exported="true" if it has an intent-filter (Android 12+ requirement)
  if ! grep -q "android:exported" "$MANIFEST_FILE" 2>/dev/null || true; then
    echo "Adding android:exported=\"true\" to the first <activity> tag (if missing)"
    # Add the exported attribute to the first <activity ...> opening tag that doesn't already include android:exported
    sed -E -n '1,/<activity/ p' "$MANIFEST_FILE" >/dev/null 2>&1 || true
    # Use sed to replace the first <activity ...> occurrence
    sed -E -i '0,/<activity/ s#<activity([^>]*)>#<activity\1 android:exported="true">#' "$MANIFEST_FILE" || true
  else
    echo "Manifest already contains android:exported somewhere; will not force-add."
  fi

  # Insert VIEW intent-filter if not present
  if ! grep -q "wemd-file-open-filter" "$MANIFEST_FILE" 2>/dev/null || true; then
    awk '
    BEGIN{printed=0}
    /<activity/ && printed==0 { print; inside=1; next }
    inside==1 && /<\/activity>/ {
      print "      <!-- wemd-file-open-filter -->"
      print "      <intent-filter android:label=\"WeMD Open Markdown\">"
      print "        <action android:name=\"android.intent.action.VIEW\" />"
      print "        <category android:name=\"android.intent.category.DEFAULT\" />"
      print "        <category android:name=\"android.intent.category.BROWSABLE\" />"
      print "        <data android:scheme=\"content\" />"
      print "        <data android:scheme=\"file\" />"
      print "        <data android:mimeType=\"text/markdown\" />"
      print "        <data android:mimeType=\"text/*\" />"
      print "        <data android:pathPattern=\".*\\.md\" />"
      print "      </intent-filter>"
      printed=1
    }
    { print }
    ' "$MANIFEST_FILE" > "${MANIFEST_FILE}.patched" && mv "${MANIFEST_FILE}.patched" "${MANIFEST_FILE}"
    echo "Inserted VIEW intent-filter into $MANIFEST_FILE"
  else
    echo "VIEW intent-filter already present in $MANIFEST_FILE"
  fi

  # Insert SEND intent-filter for ACTION_SEND (sharing) if not present
  if ! grep -q "wemd-file-send-filter" "$MANIFEST_FILE" 2>/dev/null || true; then
    awk '
    BEGIN{printed=0}
    /<activity/ && printed==0 { print; inside=1; next }
    inside==1 && /<\/activity>/ {
      print "      <!-- wemd-file-send-filter -->"
      print "      <intent-filter android:label=\"WeMD Receive Shared Markdown\">"
      print "        <action android:name=\"android.intent.action.SEND\" />"
      print "        <category android:name=\"android.intent.category.DEFAULT\" />"
      print "        <data android:mimeType=\"text/markdown\" />"
      print "        <data android:mimeType=\"text/*\" />"
      print "        <data android:mimeType=\"application/octet-stream\" />"
      print "      </intent-filter>"
      printed=1
    }
    { print }
    ' "$MANIFEST_FILE" > "${MANIFEST_FILE}.patched" && mv "${MANIFEST_FILE}.patched" "${MANIFEST_FILE}"
    echo "Inserted SEND intent-filter into $MANIFEST_FILE"
  else
    echo "SEND intent-filter already present in $MANIFEST_FILE"
  fi
fi

# 2) Modify MainActivity to handle VIEW and SEND intents (Kotlin preferred, then Java)
if [ -f "$MAIN_ACTIVITY_KT" ]; then
  if ! grep -q "// --- WeMD: support opening .md from external apps ---" "$MAIN_ACTIVITY_KT" 2>/dev/null || true; then
    cat >> "$MAIN_ACTIVITY_KT" <<'KOTLIN'

    // --- WeMD: support opening .md from external apps ---
    override fun onNewIntent(intent: android.content.Intent?) {
        super.onNewIntent(intent)
        handleIncomingIntent(intent)
    }

    override fun onCreate(savedInstanceState: android.os.Bundle?) {
        super.onCreate(savedInstanceState)
        handleIncomingIntent(intent)
    }

    private fun handleIncomingIntent(intent: android.content.Intent?) {
        if (intent == null) return
        try {
            val action = intent.action
            var uri: android.net.Uri? = null
            if (action == android.content.Intent.ACTION_VIEW) {
                uri = intent.data
            } else if (action == android.content.Intent.ACTION_SEND) {
                @Suppress("DEPRECATION")
                uri = intent.getParcelableExtra(android.content.Intent.EXTRA_STREAM) as? android.net.Uri
            }
            uri?.let { handleIncomingFile(it) }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun handleIncomingFile(uri: android.net.Uri) {
        try {
            val input = applicationContext.contentResolver.openInputStream(uri)
            if (input != null) {
                val bytes = input.readBytes()
                val base64 = android.util.Base64.encodeToString(bytes, android.util.Base64.NO_WRAP)
                val name = uri.lastPathSegment ?: "file.md"
                val js = "(function(){try{window.dispatchEvent(new CustomEvent('wemd-file-open', { detail: { name: '" + name + "', data: '" + base64 + "' } }));}catch(e){} })();"
                this.bridge?.webView?.post {
                    this.bridge?.webView?.evaluateJavascript(js, null)
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
    // --- end WeMD patch ---
KOTLIN
    echo "Patched Kotlin MainActivity at $MAIN_ACTIVITY_KT"
  else
    echo "MainActivity.kt already patched"
  fi

elif [ -f "$MAIN_ACTIVITY_JAVA" ]; then
  if ! grep -q "// --- WeMD: support opening .md from external apps ---" "$MAIN_ACTIVITY_JAVA" 2>/dev/null || true; then
    cat >> "$MAIN_ACTIVITY_JAVA" <<'JAVA'

    // --- WeMD: support opening .md from external apps ---
    @Override
    public void onNewIntent(android.content.Intent intent) {
        super.onNewIntent(intent);
        handleIncomingIntent(intent);
    }

    @Override
    protected void onCreate(android.os.Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        handleIncomingIntent(getIntent());
    }

    private void handleIncomingIntent(android.content.Intent intent) {
        if (intent == null) return;
        try {
            String action = intent.getAction();
            android.net.Uri uri = null;
            if (android.content.Intent.ACTION_VIEW.equals(action)) {
                uri = intent.getData();
            } else if (android.content.Intent.ACTION_SEND.equals(action)) {
                uri = intent.getParcelableExtra(android.content.Intent.EXTRA_STREAM);
            }
            if (uri != null) {
                handleIncomingFile(uri);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void handleIncomingFile(android.net.Uri uri) {
        try {
            java.io.InputStream input = getApplicationContext().getContentResolver().openInputStream(uri);
            if (input != null) {
                byte[] bytes = input.readAllBytes();
                String base64 = android.util.Base64.encodeToString(bytes, android.util.Base64.NO_WRAP);
                String name = uri.getLastPathSegment() != null ? uri.getLastPathSegment() : "file.md";
                String js = "(function(){try{window.dispatchEvent(new CustomEvent('wemd-file-open', { detail: { name: \""+name+"\", data: \""+base64+"\" } }));}catch(e){} })();";
                final android.webkit.WebView wv = this.bridge.getWebView();
                wv.post(() -> wv.evaluateJavascript(js, null));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // --- end WeMD patch ---
JAVA
    echo "Patched Java MainActivity at $MAIN_ACTIVITY_JAVA"
  else
    echo "MainActivity.java already patched"
  fi
else
  echo "No MainActivity.kt or MainActivity.java found at $PACKAGE_DIR - cannot patch, please check package path."
fi

echo "Patch complete."
